# Generated by Django 2.2.1 on 2019-06-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_entries', '0002_auto_20190617_1639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name_plural': 'Time entries'},
        ),
    ]
